---
title: "Untitled"
author: "tiffany60328"
date: "2020/3/25"
output: html_document
---

## Atomic vector
```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

Stacking vectors
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

Vector stacking
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```
### Character
```{r}
char1<-"你好"
char2<-'你好'
```

 小明說："明天不用上課。" 
```{r}
HeSaid<- ' 小明說："明天不用上課。"  ' 
```
### Atomic
```{r}
complexVector<- c("曉明今年歲數",("15"))
```
```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tiffany60328/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-  (c("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=2135249197")) # 
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```
```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```


 